server:
  port: 4326
spring:
  jackson:
    time-zone:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai
  application:
    name: seismic-data-server
    mvc:
      throw-exception-if-no-handler-found: true
    servlet:
      multipart:
        max-request-size: "800MB"
        max-file-size: "800MB"
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:file:e:/map-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    platform: h2
    username: sa
    password: 123
    driverClassName: org.h2.Driver
#    schema: classpath:db/schema_*.sql
#    data: classpath:db/data_*.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
#logging:
#  level: debug
